export const ArrayCarnes  = [
    {
        carne: 'ContraFile',
        preco: 30,
        id: 1,
        checked: false,
    },
    {
        carne: 'Maminha',
        preco: 49,
        id: 2,
        checked: false,
    },
    {
        carne: 'Cupim',
        preco: 34,
        id: 3,
        checked: false,
    },
    {
        carne: 'paleta',
        preco: 11,
        id: 4,
        checked: false,
    },
    {
        carne: 'Coxa',
        preco: 11,
        id: 5,
        checked: false,
    },
    {
        carne: 'Coracao',
        preco: 25,
        id: 6,
        checked: false,
    },
    {
        carne: 'Asa',
        preco: 13,
        id: 7,
        checked: false,
    },
    {
        carne: 'Picanha',
        preco: 49,
        id: 8,
        checked: false,
    },
    
    {
        carne: 'Linguica',
        preco: 15,
        id: 9,
        checked: false,
    },
    {
        carne: 'Paleta',
        preco: 31,
        id: 10,
        checked: false,
    },
    {
        carne: 'Agua',
        preco: 13,
        id: 11,
        checked: false,
    },
    {
        carne: 'Refrigerante',
        preco: 7,
        id: 12,
        checked: false,
    },
    {
        carne: 'Cerveja',
        preco: 15,
        id: 13,
        checked: false,
    },
    {
        carne: 'Suco',
        preco: 6,
        id: 14,
        checked: false,
    },
    {
        carne: 'Arroz',
        preco: 30,
        id: 15,
        checked: false,
    },
    {
        carne: 'Farofa',
        preco: 9,
        id: 16,
        checked: false,
    },
    {
        carne: 'Pao de Alho',
        preco: 10,
        id: 17,
        checked: false,
    },
    {
        carne: 'Queijo Coalho',
        preco: 23,
        id: 18,
        checked: false,
    },
    {
        carne: 'Pao Frances',
        preco: 50,
        id: 19,
        checked: false,
    },
    {
        carne: 'Carvao',
        preco: 40,
        id: 20,
        checked: false,
    },
    {
        carne: 'Prato',
        preco: 20,
        id: 21,
        checked: false,
    },
    {
        carne: 'Talheres',
        preco: 8,
        id: 22,
        checked: false,
    },
    {
        carne: 'Guardanapos',
        preco: 5,
        id: 23,
        checked: false,
    },
    {
        carne: 'Copos',
        preco: 6,
        id: 24,
        checked: false,
    },
    
]